spring:
  datasource:
    url: jdbc:postgresql://p466-postgres-tarashbudhrani.postgres.database.azure.com:5432/primes
    username: tarashbudhrani@p466-postgres-tarashbudhrani
    password: StrongTarash@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
