name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SERVICE_VERSION: ${{ secrets.SERVICE_VERSION }}
      SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
      SPRING_DATASOURCE_UN: ${{ secrets.SPRING_DATASOURCE_UN }}
      SPRING_DATASOURCE_PW: ${{ secrets.SPRING_DATASOURCE_PW }}
      REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        run: run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t $REGISTRY_URL/primes-service:$SERVICE_VERSION .

      - name: Login to Azure Container Registry
        run: echo $REGISTRY_PASSWORD | docker login $REGISTRY_URL -u $REGISTRY_USERNAME --password-stdin

      - name: Push Docker image
        run: docker push $REGISTRY_URL/primes-service:$SERVICE_VERSION

      - name: Set up kubectl
        run: |
          echo "$KUBE_CONFIG" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/deploy.yaml
